fix(ci): test

diff --git a/.github/workflows/release-python.yml b/.github/workflows/release-python.yml
--- a/.github/workflows/release-python.yml
+++ b/.github/workflows/release-python.yml
@@ -13,6 +13,12 @@ jobs:
     name: Release new version to PyPI
     runs-on: ubuntu-latest
     steps:
+      - name: Check version format vMAJOR.MINOR.PATCH(-SUFFIX)
+        run: |
+          if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)?$ ]]; then
+            echo "Invalid version format. Expected vMAJOR.MINOR.PATCH(-SUFFIX)?, got ${GITHUB_REF_NAME}"
+            exit 1
+          fi
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Install the project
@@ -23,22 +29,18 @@ jobs:
           private-pypi-user: ${{ secrets.PRIV_PIP_USER }}
           private-pypi-pass: ${{ secrets.PRIV_PIP_PASSWORD }}
           python-version: "${{ env.PYTHON_VERSION }}"
-      - name: Check version format vMAJOR.MINOR.PATCH(-SUFFIX)
+      - name: Unshallow
         run: |
-          if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)?$ ]]; then
-            echo "Invalid version format. Expected vMAJOR.MINOR.PATCH(-SUFFIX)?, got ${GITHUB_REF_NAME}"
-            exit 1
-          fi
-      - name: Bump version
+          git fetch --prune --unshallow
+      - name: Bump version in pyproject.toml
+        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
         run: |
           echo "Github ref ${GITHUB_REF_NAME:1}"
           poetry version ${GITHUB_REF_NAME:1}
-      - name: Commit and push
-        run: |
           git config --local user.email "" # Set empty email
           git config --local user.name "GitHub Action"
           git add pyproject.toml
-          git commit -m "chore(ci): bump pyproject.toml version to ${GITHUB_REF_NAME:1}"
+          git commit -m "chore: release version ${GITHUB_REF_NAME:1} [skip ci]"
           git push
       - name: Publish
         run: poetry publish --build -n -r dronetag
